// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: first_query.sql

package db

import (
	"context"
)

const createSuggestion = `-- name: CreateSuggestion :exec
INSERT INTO suggestions (user_chat_id, user_message_id, bot_message_id)
VALUES ($1, $2, $3)
`

type CreateSuggestionParams struct {
	UserChatID    int64
	UserMessageID int64
	BotMessageID  int64
}

func (q *Queries) CreateSuggestion(ctx context.Context, arg CreateSuggestionParams) error {
	_, err := q.db.Exec(ctx, createSuggestion, arg.UserChatID, arg.UserMessageID, arg.BotMessageID)
	return err
}

const getSender = `-- name: GetSender :one
SELECT user_chat_id, user_message_id FROM suggestions
WHERE bot_message_id = $1
`

type GetSenderRow struct {
	UserChatID    int64
	UserMessageID int64
}

func (q *Queries) GetSender(ctx context.Context, botMessageID int64) (GetSenderRow, error) {
	row := q.db.QueryRow(ctx, getSender, botMessageID)
	var i GetSenderRow
	err := row.Scan(&i.UserChatID, &i.UserMessageID)
	return i, err
}
