// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Suggestion struct {
	ID            pgtype.UUID
	UserChatID    int64
	UserMessageID int64
	BotMessageID  int64
	IsAnswered    pgtype.Bool
}
